FROM node:10

# Application
ARG NODE_ENV=development
ARG BRFENERGI_LANG=sv
ARG FORUM_URL
ARG URL_ENCRYPTION_KEY
ARG BRFENERGI_SERVICE_URL=https://brfenergi.se
ARG BRFENERGI_SESSION_SECRET
ARG BRFENERGI_USER
ARG BRFENERGI_PASS

# Services
ARG MAPBOX_ACCESS_TOKEN
ARG MAPBOX_STYLE
ARG GOOGLE_ANALYTICS_ID
ARG GOOGLE_GEOCODE_KEY
ARG IPSTACK_KEY

# Metry credentials
ARG METRY_CLIENT_ID
ARG METRY_CLIENT_SECRET
ARG METRY_OPEN_CHANNEL
ARG METRY_ENDPOINT=https://metry-development.herokuapp.com/api/v2/

# CMS
ARG PRISMIC_API=https://brf-energi.cdn.prismic.io/api/v2

# Database
ARG MONGO_URL

# Assign environment variables
ENV PORT 8080
ENV NODE_ENV $NODE_ENV
ENV BRFENERGI_LANG $BRFENERGI_LANG
ENV FORUM_URL $FORUM_URL
ENV URL_ENCRYPTION_KEY $URL_ENCRYPTION_KEY
ENV BRFENERGI_SERVICE_URL $BRFENERGI_SERVICE_URL
ENV BRFENERGI_SESSION_SECRET $BRFENERGI_SESSION_SECRET
ENV BRFENERGI_USER $BRFENERGI_USER
ENV BRFENERGI_PASS $BRFENERGI_PASS
ENV MAPBOX_ACCESS_TOKEN $MAPBOX_ACCESS_TOKEN
ENV MAPBOX_STYLE $MAPBOX_STYLE
ENV GOOGLE_ANALYTICS_ID $GOOGLE_ANALYTICS_ID
ENV GOOGLE_GEOCODE_KEY $GOOGLE_GEOCODE_KEY
ENV IPSTACK_KEY $IPSTACK_KEY
ENV METRY_CLIENT_ID $METRY_CLIENT_ID
ENV METRY_CLIENT_SECRET $METRY_CLIENT_SECRET
ENV METRY_OPEN_CHANNEL $METRY_OPEN_CHANNEL
ENV METRY_ENDPOINT $METRY_ENDPOINT
ENV PRISMIC_API $PRISMIC_API
ENV MONGO_URL $MONGO_URL

# Create directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN if [ "$NODE_ENV" != "development" ]; then npm ci --only=production; else npm install; fi

# Copy files
COPY . .

# Expose port
EXPOSE 8080

# Build client
RUN npm run build

# Start server
CMD npm start
